Arduino python scripts
tensorflow/tflite-micro-arduino-examples pull request #4
Opened 2021-07-21 00:06 UTC by ddavis-2015

Arduino library creation for CI build
Issue# 3
bug=3

2021-07-22 22:10 UTC, advaitjain requested changes
let's split this PR into two PRs:

1. copy over all the files from tflite-micro that will live in the current repo once this work is complete
2. PR with only the new code that you have written for the sync -- I'm assuming that is the manifest.ini and the create_tflm_arduino.py

Also, let's put the files in micro/tools/make, micro/tools/ci_build and micro/tools/project_generation into a top level ci/ or scripts/ directory.

I don't have a preference for the name of the directory, but would like to have a separate top-level directory with all the code needed to handle the sync and Arduino library generation (rather than being nested within the src/tensorflow tree).

2021-07-22 23:57 UTC, advaitjain requested changes
I haven't reviewed all of the code yet. happy to chat more tomorrow.

2021-07-22 23:57 UTC, advaitjain commented on src/tensorflow/lite/micro/tools/project_generation/create_tflm_arduino.py
> +    cmd += f" {args}"
combining string concatenation with f-strings seems to defeat the purpose of f-strings.

2021-07-22 23:57 UTC, advaitjain commented on src/tensorflow/lite/micro/tools/project_generation/create_tflm_arduino.py
> +  cmd += f" < {file_path!s}"
I think we need to enforce a few conditions on the parameters to this function:

args: must not be an empty string
scripts: must not be an empty list

The we can replace all of these with:

```py
cmd = f"sed {args} -E {" -E ".join(scripts)} {str(file_path)}"
```

Note that `{file_path!s}` is a bit too fancy for me. Let's use the more explicit `str(file_path)`

2021-07-22 23:57 UTC, advaitjain commented on src/tensorflow/lite/micro/tools/project_generation/create_tflm_arduino.py
> +                            stderr=subprocess.PIPE)
let's also capture the error code and raise an exception if the command did not succeed.

Similar to:
https://github.com/tensorflow/tflite-micro/blob/43265614fe010c677c447c1269500478b49e72dd/tensorflow/lite/micro/tools/project_generation/create_tflm_tree.py#L53-L57

2021-07-22 23:57 UTC, advaitjain commented on src/tensorflow/lite/micro/tools/project_generation/create_tflm_arduino.py
> +def RunSedScripts(file_path: Path,
naming nit: _run_sed_scripts

https://google.github.io/styleguide/pyguide.html#316-naming

2021-07-22 23:57 UTC, advaitjain commented on src/tensorflow/lite/micro/tools/project_generation/create_tflm_arduino.py
> +def RemoveDirectories(paths: List[Path], is_dry_run: bool = True) -> None:
_remove_directories

2021-07-22 23:57 UTC, advaitjain commented on src/tensorflow/lite/micro/tools/project_generation/create_tflm_arduino.py
> +                           is_dry_run: bool = True) -> None:
not clear to me why in the overal generation process we will have empty directories. Let's talk about the need for this function.

2021-07-22 23:57 UTC, advaitjain commented on src/tensorflow/lite/micro/tools/project_generation/create_tflm_arduino.py
> +  cmd += f" {args}"
```py
cmd = f"python3 {path_to_script} {args}"
```

2021-07-22 23:57 UTC, advaitjain commented on src/tensorflow/lite/micro/tools/project_generation/create_tflm_arduino.py
> +
please catch errors in the scripts and raise exceptions.

2021-07-22 23:57 UTC, advaitjain commented on src/tensorflow/lite/micro/tools/project_generation/create_tflm_arduino.py
> +def RunPythonScript(path_to_script: Path,
doesn't look like we need `path_to_script` to be of type Path. str seems sufficient here.

2021-07-22 23:57 UTC, advaitjain commented on src/tensorflow/lite/micro/tools/project_generation/create_tflm_arduino.py
> +  dir_path: Path
remove.

2021-07-22 23:57 UTC, advaitjain commented on src/tensorflow/lite/micro/tools/project_generation/create_tflm_arduino.py
> +  for dir_path in paths:
dir_path is not the correct name for this variable. my preference would be to have two lists, src and dest.

we can have a precondition to check that the two lists are of the same length.

2021-07-22 23:57 UTC, advaitjain commented on src/tensorflow/lite/micro/tools/project_generation/create_tflm_arduino.py
> +  dir_path: Tuple[Path, Path]
remove, not necessary.

2021-07-27 18:11 UTC, advaitjain requested changes

2021-07-27 18:11 UTC, advaitjain commented on scripts/create_tflm_arduino.py
> +        self.Manifest.PATCH_SED]
why not assign self.add_list etc. in the _parse_manifest function? Then we won't need to create and think about the intermediate dict struct.

2021-07-27 18:11 UTC, advaitjain commented on scripts/create_tflm_arduino.py
> +      pass
what is this for?

2021-07-27 18:11 UTC, advaitjain commented on scripts/create_tflm_arduino.py
> +    """
Let's discuss what we want the script output to be. I would prefer this script to change the repository in-place with updated files from tflite-micro unless that would become quite a bit more complex.

2021-07-27 18:59 UTC, ddavis-2015 commented on scripts/MANIFEST.ini
> +# without modification to the output directory.
This will be in the README.md in the scripts directory

2021-08-02 21:16 UTC, advaitjain approved these changes

2021-08-02 21:16 UTC, merged